export enum WeatherActions {
    WEATHER_RECEIVE_ICONS = 'WEATHER_RECEIVE_ICONS',
    WEATHER_RECEIVE_LOCATION = 'WEATHER_RECEIVE_LOCATION',
    WEATHER_RECEIVE_AIR_POLLUTION = 'WEATHER_RECEIVE_AIR_POLLUTION',
    WEATHER_RECEIVE_CURRENT_AND_FORECAST = 'WEATHER_RECEIVE_CURRENT_AND_FORECAST',
    WEATHER_ERROR = 'WEATHER_ERROR',
}
